From 29b8ecb62f28a7fff7fbf3dd2ed14a6d798b1c98 Mon Sep 17 00:00:00 2001
From: Lei Maohui <leimaohui@fujitsu.com>
Date: Thu, 19 Dec 2024 03:12:58 +0000
Subject: [PATCH 2/2] python_message.py: Fix No module named 'six.moves' on
 ubuntu24.04 with python3.12.

Signed-off-by: Lei Maohui <leimaohui@fujitsu.com>
---
 .../protobuf/python/google/protobuf/internal/python_message.py   | 1 -
 1 file changed, 1 deletion(-)

diff --git a/third_party/protobuf/python/google/protobuf/internal/python_message.py b/third_party/protobuf/python/google/protobuf/internal/python_message.py
index 803ae8484..d9ed9f91f 100755
--- a/third_party/protobuf/python/google/protobuf/internal/python_message.py
+++ b/third_party/protobuf/python/google/protobuf/internal/python_message.py
@@ -56,7 +56,6 @@ import sys
 import weakref
 
 import six
-from six.moves import range
 
 # We use "as" to avoid name collisions with variables.
 from google.protobuf.internal import api_implementation
-- 
2.43.0

